spring:
  datasource:
    url: jdbc:mysql://localhost:3306/linkyway?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
    #        use_sql_comments: true
    open-in-view: false

  config:
    import:
      - classpath:jwt.yml
      - classpath:folder.yml


