spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;   # http://localhost:8080/h2-console
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


    properties.hibernate.hbm2ddl.auto: create

    showSql: true