spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;  # http://localhost:8080/h2-console
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate-ddl: true
        highlight_sql: true
    #        use_sql_comments: true
    open-in-view: false

  batch:
    initialize-schema: always
    job:
      enabled: false
      names: ${job.name:batchJob}

  config:
    import:
      - classpath:jwt.yml
      - classpath:folder.yml


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
