spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;  # http://localhost:8080/h2-console
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
#        use_sql_comments: true
  config:
    import:
      - classpath:jwt.yml


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
