name: Spring Boot Gradle CI/CD

on:
  push:
    branches: [ feat/#163/github_actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --stacktrace

      - name: ls
        run: ls

#      - name: Make Directory
#        run: mkdir deploy
#
#      - name: Copy All Project
#        run: cp -r ./* ./deploy/

      - name: Make zip file
        run: zip -r -qq -j ./linkyway-build.zip ./

      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \
          ./linkyway-build.zip s3://${{ secrets.AWS_STAGING_BUCKET_NAME }}/
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name linky-way-back \
          --deployment-group-name linky-way-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_STAGING_BUCKET_NAME }},bundleType=zip,key=linkyway-build.zip \
          --region ap-northeast-2